Update pr-validate-branch.yml

diff --git a/.github/workflows/pr-validate-branch.yml b/.github/workflows/pr-validate-branch.yml
--- a/.github/workflows/pr-validate-branch.yml
+++ b/.github/workflows/pr-validate-branch.yml
@@ -105,6 +105,15 @@ jobs:
               if: ${{ env.APEX_TESTS != '' }}
               run: |
                   node qualityGateCheck.js
+                  QUALITY_CHECK=$(cat ./testResults/codeCoverageReadableFile.txt)
+                  echo "QUALITY_CHECK=$QUALITY_CHECK" >> $GITHUB_ENV
+
+            - name: 'If the Code Coverage for any class is > 85% Exit'
+              if: ${{ env.QUALITY_CHECK != 'true' }}
+              run: |
+                  echo "Some Test Cases Failed Check below for more details:"
+                  echo ${{env.QUALITY_CHECK}}
+                  exit 1
 
             # Validate the changes and run the testCases if required
             # - name: 'Validate changes present in package.xml - Run Tests'
